from ai.prompts.constants import (
    TRIAGE_SYSTEM_PROMPT,
    FIT_AGENT_PROMPT,
    STYLIST_AGENT_PROMPT,
    SPECIALIST_INPUT_TEMPLATE,
    PREVIOUS_ANSWERS_TEMPLATE,
    RETRY_FEEDBACK_TEMPLATE,
    QUALITY_SYSTEM_PROMPT,
    QUALITY_USER_PROMPT,
    COMPOSE_PROMPT,
    NOT_APPROVED_NOTE,
)


__all__ = [
    "TRIAGE_SYSTEM_PROMPT",
    "FIT_AGENT_PROMPT",
    "STYLIST_AGENT_PROMPT",
    "SPECIALIST_INPUT_TEMPLATE",
    "PREVIOUS_ANSWERS_TEMPLATE",
    "RETRY_FEEDBACK_TEMPLATE",
    "QUALITY_SYSTEM_PROMPT",
    "QUALITY_USER_PROMPT",
    "COMPOSE_PROMPT",
    "NOT_APPROVED_NOTE",
]
